mysql:
  addr: localhost:3306
  username: root
  password: root
  charset: utf8mb4
  database: TikTok

redis:
  addr: localhost:6379

rabbitmq:
  addr: localhost:5672
  username: guest
  password: guest

etcd:
  addr: localhost:2379