# 通信安全配置
communication_security:
  # TLS配置
  tls:
    enabled: true
    min_version: "1.2"
    max_version: "1.3"
    cert_file: "/etc/ssl/certs/server.crt"
    key_file: "/etc/ssl/private/server.key"
    ca_file: "/etc/ssl/certs/ca.crt"
    cipher_suites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
    
    # 证书轮换
    certificate_rotation:
      enabled: true
      check_interval: "24h"
      renewal_threshold: "720h" # 30天
      auto_reload: true

  # JWT安全配置
  jwt:
    # 密钥配置
    signing_method: "RS256"
    private_key_file: "/etc/ssl/private/jwt_private.pem"
    public_key_file: "/etc/ssl/certs/jwt_public.pem"
    
    # Token配置
    access_token:
      expiration: "15m"
      refresh_threshold: "5m"
    refresh_token:
      expiration: "7d"
      rotation_enabled: true
    
    # 安全特性
    security:
      enable_jti: true # JWT ID
      enable_blacklist: true
      blacklist_cleanup_interval: "1h"
      max_token_age: "24h"
      require_secure_transport: true
      
    # 声明配置
    claims:
      issuer: "tiktok-service"
      audience: "tiktok-users"
      include_user_roles: true
      include_permissions: true
      include_device_info: true
      include_ip_address: true

  # 加密通信配置
  encryption:
    # 混合加密
    hybrid_encryption:
      enabled: true
      rsa_key_size: 4096
      aes_key_size: 256
      key_rotation_interval: "30d"
      
    # 消息完整性
    message_integrity:
      enable_signature: true
      signature_algorithm: "RSA-PSS"
      hash_algorithm: "SHA-256"
      timestamp_tolerance: "5m"
      
    # 密钥管理
    key_management:
      key_derivation_iterations: 100000
      salt_size: 16
      enable_perfect_forward_secrecy: true

  # 限流配置
  rate_limiting:
    # 全局限流
    global:
      enabled: true
      algorithm: "sliding_window"
      max_requests: 10000
      window_size: "1m"
      
    # 用户级限流
    user_level:
      enabled: true
      algorithm: "token_bucket"
      bucket_size: 100
      refill_rate: 10
      refill_interval: "1s"
      
    # IP级限流
    ip_level:
      enabled: true
      algorithm: "fixed_window"
      max_requests: 1000
      window_size: "1m"
      
    # 自适应限流
    adaptive:
      enabled: true
      load_threshold: 0.8
      adjust_factor: 0.5
      monitor_interval: "30s"
      
    # API级限流
    api_level:
      "/v1/user/login":
        max_requests: 5
        window_size: "1m"
        algorithm: "sliding_window"
      "/v1/video/upload":
        max_requests: 10
        window_size: "5m"
        algorithm: "token_bucket"
      "/v1/interaction/like":
        max_requests: 60
        window_size: "1m"
        algorithm: "sliding_window"

  # 熔断器配置
  circuit_breaker:
    enabled: true
    default_config:
      max_failures: 5
      reset_timeout: "60s"
      half_open_max_calls: 3
      
    services:
      user_service:
        max_failures: 3
        reset_timeout: "30s"
      video_service:
        max_failures: 5
        reset_timeout: "60s"
      interaction_service:
        max_failures: 10
        reset_timeout: "30s"

  # 安全头配置
  security_headers:
    enabled: true
    headers:
      "Strict-Transport-Security": "max-age=31536000; includeSubDomains"
      "X-Content-Type-Options": "nosniff"
      "X-Frame-Options": "DENY"
      "X-XSS-Protection": "1; mode=block"
      "Content-Security-Policy": "default-src 'self'"
      "Referrer-Policy": "strict-origin-when-cross-origin"

  # 输入验证配置
  input_validation:
    enabled: true
    max_request_size: "10MB"
    max_header_size: "8KB"
    max_uri_length: 2048
    
    # 内容过滤
    content_filtering:
      enable_xss_protection: true
      enable_sql_injection_protection: true
      enable_command_injection_protection: true
      custom_patterns:
        - "(?i)(script|javascript|vbscript)"
        - "(?i)(union|select|insert|update|delete|drop)"

  # 审计日志配置
  audit_logging:
    enabled: true
    log_level: "info"
    log_format: "json"
    
    # 记录的事件类型
    events:
      - "authentication"
      - "authorization"
      - "rate_limit_exceeded"
      - "circuit_breaker_opened"
      - "encryption_failure"
      - "certificate_rotation"
      
    # 敏感信息脱敏
    sensitive_fields:
      - "password"
      - "token"
      - "private_key"
      - "session_id"

  # 监控和告警配置
  monitoring:
    enabled: true
    metrics_interval: "30s"
    
    # 监控指标
    metrics:
      - "request_rate"
      - "error_rate"
      - "response_time"
      - "circuit_breaker_state"
      - "rate_limit_hits"
      - "tls_handshake_time"
      - "jwt_validation_time"
      
    # 告警阈值
    alerts:
      high_error_rate:
        threshold: 5.0 # 5%
        duration: "5m"
      high_response_time:
        threshold: "1s"
        duration: "2m"
      rate_limit_abuse:
        threshold: 100 # 每分钟被限流次数
        duration: "1m"

# 开发环境配置
development:
  # 调试模式
  debug_mode: false
  
  # 测试配置
  testing:
    disable_tls: false
    mock_encryption: false
    bypass_rate_limiting: false
    
  # 性能分析
  profiling:
    enabled: false
    cpu_profile: false
    memory_profile: false
    
# 生产环境安全加固
production_hardening:
  # 禁用不安全的功能
  disable_debug_endpoints: true
  disable_metrics_endpoint: false
  disable_health_check: false
  
  # 安全策略
  security_policies:
    enforce_https: true
    require_client_certificates: false
    enable_hsts: true
    enable_csrf_protection: true
    
  # 资源限制
  resource_limits:
    max_connections: 10000
    max_requests_per_connection: 1000
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "120s"