// Code generated by Kitex v0.10.3. DO NOT EDIT.

package followservice

import (
	relations "HuaTug.com/kitex_gen/relations"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"RelationService": kitex.NewMethodInfo(
		relationServiceHandler,
		newFollowServiceRelationServiceArgs,
		newFollowServiceRelationServiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FollowingList": kitex.NewMethodInfo(
		followingListHandler,
		newFollowServiceFollowingListArgs,
		newFollowServiceFollowingListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FollowerList": kitex.NewMethodInfo(
		followerListHandler,
		newFollowServiceFollowerListArgs,
		newFollowServiceFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FriendList": kitex.NewMethodInfo(
		friendListHandler,
		newFollowServiceFriendListArgs,
		newFollowServiceFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	followServiceServiceInfo                = NewServiceInfo()
	followServiceServiceInfoForClient       = NewServiceInfoForClient()
	followServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return followServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return followServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return followServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FollowService"
	handlerType := (*relations.FollowService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "relations",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func relationServiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relations.FollowServiceRelationServiceArgs)
	realResult := result.(*relations.FollowServiceRelationServiceResult)
	success, err := handler.(relations.FollowService).RelationService(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowServiceRelationServiceArgs() interface{} {
	return relations.NewFollowServiceRelationServiceArgs()
}

func newFollowServiceRelationServiceResult() interface{} {
	return relations.NewFollowServiceRelationServiceResult()
}

func followingListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relations.FollowServiceFollowingListArgs)
	realResult := result.(*relations.FollowServiceFollowingListResult)
	success, err := handler.(relations.FollowService).FollowingList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowServiceFollowingListArgs() interface{} {
	return relations.NewFollowServiceFollowingListArgs()
}

func newFollowServiceFollowingListResult() interface{} {
	return relations.NewFollowServiceFollowingListResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relations.FollowServiceFollowerListArgs)
	realResult := result.(*relations.FollowServiceFollowerListResult)
	success, err := handler.(relations.FollowService).FollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowServiceFollowerListArgs() interface{} {
	return relations.NewFollowServiceFollowerListArgs()
}

func newFollowServiceFollowerListResult() interface{} {
	return relations.NewFollowServiceFollowerListResult()
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relations.FollowServiceFriendListArgs)
	realResult := result.(*relations.FollowServiceFriendListResult)
	success, err := handler.(relations.FollowService).FriendList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowServiceFriendListArgs() interface{} {
	return relations.NewFollowServiceFriendListArgs()
}

func newFollowServiceFriendListResult() interface{} {
	return relations.NewFollowServiceFriendListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RelationService(ctx context.Context, req *relations.RelationServiceRequest) (r *relations.RelationServiceResponse, err error) {
	var _args relations.FollowServiceRelationServiceArgs
	_args.Req = req
	var _result relations.FollowServiceRelationServiceResult
	if err = p.c.Call(ctx, "RelationService", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowingList(ctx context.Context, req *relations.FollowingListRequest) (r *relations.FollowingListResponse, err error) {
	var _args relations.FollowServiceFollowingListArgs
	_args.Req = req
	var _result relations.FollowServiceFollowingListResult
	if err = p.c.Call(ctx, "FollowingList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, req *relations.FollowerListRequest) (r *relations.FollowerListResponse, err error) {
	var _args relations.FollowServiceFollowerListArgs
	_args.Req = req
	var _result relations.FollowServiceFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, req *relations.FriendListRequest) (r *relations.FriendListResponse, err error) {
	var _args relations.FollowServiceFriendListArgs
	_args.Req = req
	var _result relations.FollowServiceFriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
