// Code generated by Kitex v0.14.1. DO NOT EDIT.

package userservice

import (
	users "HuaTug.com/kitex_gen/users"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UpdateUser": kitex.NewMethodInfo(
		updateUserHandler,
		newUserServiceUpdateUserArgs,
		newUserServiceUpdateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUser": kitex.NewMethodInfo(
		deleteUserHandler,
		newUserServiceDeleteUserArgs,
		newUserServiceDeleteUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUser": kitex.NewMethodInfo(
		queryUserHandler,
		newUserServiceQueryUserArgs,
		newUserServiceQueryUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateUser": kitex.NewMethodInfo(
		createUserHandler,
		newUserServiceCreateUserArgs,
		newUserServiceCreateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LoginUser": kitex.NewMethodInfo(
		loginUserHandler,
		newUserServiceLoginUserArgs,
		newUserServiceLoginUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckUserExistsById": kitex.NewMethodInfo(
		checkUserExistsByIdHandler,
		newUserServiceCheckUserExistsByIdArgs,
		newUserServiceCheckUserExistsByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"VerifyCode": kitex.NewMethodInfo(
		verifyCodeHandler,
		newUserServiceVerifyCodeArgs,
		newUserServiceVerifyCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendCode": kitex.NewMethodInfo(
		sendCodeHandler,
		newUserServiceSendCodeArgs,
		newUserServiceSendCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ForgotPassword": kitex.NewMethodInfo(
		forgotPasswordHandler,
		newUserServiceForgotPasswordArgs,
		newUserServiceForgotPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPassword": kitex.NewMethodInfo(
		resetPasswordHandler,
		newUserServiceResetPasswordArgs,
		newUserServiceResetPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMyProfile": kitex.NewMethodInfo(
		getMyProfileHandler,
		newUserServiceGetMyProfileArgs,
		newUserServiceGetMyProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAvatarUploadUrl": kitex.NewMethodInfo(
		getAvatarUploadUrlHandler,
		newUserServiceGetAvatarUploadUrlArgs,
		newUserServiceGetAvatarUploadUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAvatar": kitex.NewMethodInfo(
		updateAvatarHandler,
		newUserServiceUpdateAvatarArgs,
		newUserServiceUpdateAvatarResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newUserServiceChangePasswordArgs,
		newUserServiceChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*users.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "users",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func updateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceUpdateUserArgs)
	realResult := result.(*users.UserServiceUpdateUserResult)
	success, err := handler.(users.UserService).UpdateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserArgs() interface{} {
	return users.NewUserServiceUpdateUserArgs()
}

func newUserServiceUpdateUserResult() interface{} {
	return users.NewUserServiceUpdateUserResult()
}

func deleteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceDeleteUserArgs)
	realResult := result.(*users.UserServiceDeleteUserResult)
	success, err := handler.(users.UserService).DeleteUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceDeleteUserArgs() interface{} {
	return users.NewUserServiceDeleteUserArgs()
}

func newUserServiceDeleteUserResult() interface{} {
	return users.NewUserServiceDeleteUserResult()
}

func queryUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceQueryUserArgs)
	realResult := result.(*users.UserServiceQueryUserResult)
	success, err := handler.(users.UserService).QueryUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQueryUserArgs() interface{} {
	return users.NewUserServiceQueryUserArgs()
}

func newUserServiceQueryUserResult() interface{} {
	return users.NewUserServiceQueryUserResult()
}

func createUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceCreateUserArgs)
	realResult := result.(*users.UserServiceCreateUserResult)
	success, err := handler.(users.UserService).CreateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateUserArgs() interface{} {
	return users.NewUserServiceCreateUserArgs()
}

func newUserServiceCreateUserResult() interface{} {
	return users.NewUserServiceCreateUserResult()
}

func loginUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceLoginUserArgs)
	realResult := result.(*users.UserServiceLoginUserResult)
	success, err := handler.(users.UserService).LoginUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginUserArgs() interface{} {
	return users.NewUserServiceLoginUserArgs()
}

func newUserServiceLoginUserResult() interface{} {
	return users.NewUserServiceLoginUserResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceGetUserInfoArgs)
	realResult := result.(*users.UserServiceGetUserInfoResult)
	success, err := handler.(users.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return users.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return users.NewUserServiceGetUserInfoResult()
}

func checkUserExistsByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceCheckUserExistsByIdArgs)
	realResult := result.(*users.UserServiceCheckUserExistsByIdResult)
	success, err := handler.(users.UserService).CheckUserExistsById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCheckUserExistsByIdArgs() interface{} {
	return users.NewUserServiceCheckUserExistsByIdArgs()
}

func newUserServiceCheckUserExistsByIdResult() interface{} {
	return users.NewUserServiceCheckUserExistsByIdResult()
}

func verifyCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceVerifyCodeArgs)
	realResult := result.(*users.UserServiceVerifyCodeResult)
	success, err := handler.(users.UserService).VerifyCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceVerifyCodeArgs() interface{} {
	return users.NewUserServiceVerifyCodeArgs()
}

func newUserServiceVerifyCodeResult() interface{} {
	return users.NewUserServiceVerifyCodeResult()
}

func sendCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceSendCodeArgs)
	realResult := result.(*users.UserServiceSendCodeResult)
	success, err := handler.(users.UserService).SendCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSendCodeArgs() interface{} {
	return users.NewUserServiceSendCodeArgs()
}

func newUserServiceSendCodeResult() interface{} {
	return users.NewUserServiceSendCodeResult()
}

func forgotPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceForgotPasswordArgs)
	realResult := result.(*users.UserServiceForgotPasswordResult)
	success, err := handler.(users.UserService).ForgotPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceForgotPasswordArgs() interface{} {
	return users.NewUserServiceForgotPasswordArgs()
}

func newUserServiceForgotPasswordResult() interface{} {
	return users.NewUserServiceForgotPasswordResult()
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceResetPasswordArgs)
	realResult := result.(*users.UserServiceResetPasswordResult)
	success, err := handler.(users.UserService).ResetPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceResetPasswordArgs() interface{} {
	return users.NewUserServiceResetPasswordArgs()
}

func newUserServiceResetPasswordResult() interface{} {
	return users.NewUserServiceResetPasswordResult()
}

func getMyProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceGetMyProfileArgs)
	realResult := result.(*users.UserServiceGetMyProfileResult)
	success, err := handler.(users.UserService).GetMyProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetMyProfileArgs() interface{} {
	return users.NewUserServiceGetMyProfileArgs()
}

func newUserServiceGetMyProfileResult() interface{} {
	return users.NewUserServiceGetMyProfileResult()
}

func getAvatarUploadUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceGetAvatarUploadUrlArgs)
	realResult := result.(*users.UserServiceGetAvatarUploadUrlResult)
	success, err := handler.(users.UserService).GetAvatarUploadUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetAvatarUploadUrlArgs() interface{} {
	return users.NewUserServiceGetAvatarUploadUrlArgs()
}

func newUserServiceGetAvatarUploadUrlResult() interface{} {
	return users.NewUserServiceGetAvatarUploadUrlResult()
}

func updateAvatarHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceUpdateAvatarArgs)
	realResult := result.(*users.UserServiceUpdateAvatarResult)
	success, err := handler.(users.UserService).UpdateAvatar(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateAvatarArgs() interface{} {
	return users.NewUserServiceUpdateAvatarArgs()
}

func newUserServiceUpdateAvatarResult() interface{} {
	return users.NewUserServiceUpdateAvatarResult()
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*users.UserServiceChangePasswordArgs)
	realResult := result.(*users.UserServiceChangePasswordResult)
	success, err := handler.(users.UserService).ChangePassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceChangePasswordArgs() interface{} {
	return users.NewUserServiceChangePasswordArgs()
}

func newUserServiceChangePasswordResult() interface{} {
	return users.NewUserServiceChangePasswordResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UpdateUser(ctx context.Context, req *users.UpdateUserRequest) (r *users.UpdateUserResponse, err error) {
	var _args users.UserServiceUpdateUserArgs
	_args.Req = req
	var _result users.UserServiceUpdateUserResult
	if err = p.c.Call(ctx, "UpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUser(ctx context.Context, req *users.DeleteUserRequest) (r *users.DeleteUserResponse, err error) {
	var _args users.UserServiceDeleteUserArgs
	_args.Req = req
	var _result users.UserServiceDeleteUserResult
	if err = p.c.Call(ctx, "DeleteUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUser(ctx context.Context, req *users.QueryUserRequest) (r *users.QueryUserResponse, err error) {
	var _args users.UserServiceQueryUserArgs
	_args.Req = req
	var _result users.UserServiceQueryUserResult
	if err = p.c.Call(ctx, "QueryUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateUser(ctx context.Context, req *users.CreateUserRequest) (r *users.CreateUserResponse, err error) {
	var _args users.UserServiceCreateUserArgs
	_args.Req = req
	var _result users.UserServiceCreateUserResult
	if err = p.c.Call(ctx, "CreateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginUser(ctx context.Context, req *users.LoginUserResquest) (r *users.LoginUserResponse, err error) {
	var _args users.UserServiceLoginUserArgs
	_args.Req = req
	var _result users.UserServiceLoginUserResult
	if err = p.c.Call(ctx, "LoginUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *users.GetUserInfoRequest) (r *users.GetUserInfoResponse, err error) {
	var _args users.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result users.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckUserExistsById(ctx context.Context, req *users.CheckUserExistsByIdRequst) (r *users.CheckUserExistsByIdResponse, err error) {
	var _args users.UserServiceCheckUserExistsByIdArgs
	_args.Req = req
	var _result users.UserServiceCheckUserExistsByIdResult
	if err = p.c.Call(ctx, "CheckUserExistsById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyCode(ctx context.Context, req *users.VerifyCodeRequest) (r *users.VerifyCodeResponse, err error) {
	var _args users.UserServiceVerifyCodeArgs
	_args.Req = req
	var _result users.UserServiceVerifyCodeResult
	if err = p.c.Call(ctx, "VerifyCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendCode(ctx context.Context, req *users.SendCodeRequest) (r *users.SendCodeResponse, err error) {
	var _args users.UserServiceSendCodeArgs
	_args.Req = req
	var _result users.UserServiceSendCodeResult
	if err = p.c.Call(ctx, "SendCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ForgotPassword(ctx context.Context, req *users.ForgotPasswordRequest) (r *users.ForgotPasswordResponse, err error) {
	var _args users.UserServiceForgotPasswordArgs
	_args.Req = req
	var _result users.UserServiceForgotPasswordResult
	if err = p.c.Call(ctx, "ForgotPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPassword(ctx context.Context, req *users.ResetPasswordRequest) (r *users.ResetPasswordResponse, err error) {
	var _args users.UserServiceResetPasswordArgs
	_args.Req = req
	var _result users.UserServiceResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMyProfile(ctx context.Context, req *users.GetMyProfileRequest) (r *users.GetMyProfileResponse, err error) {
	var _args users.UserServiceGetMyProfileArgs
	_args.Req = req
	var _result users.UserServiceGetMyProfileResult
	if err = p.c.Call(ctx, "GetMyProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAvatarUploadUrl(ctx context.Context, req *users.GetAvatarUploadUrlRequest) (r *users.GetAvatarUploadUrlResponse, err error) {
	var _args users.UserServiceGetAvatarUploadUrlArgs
	_args.Req = req
	var _result users.UserServiceGetAvatarUploadUrlResult
	if err = p.c.Call(ctx, "GetAvatarUploadUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAvatar(ctx context.Context, req *users.UpdateAvatarRequest) (r *users.UpdateAvatarResponse, err error) {
	var _args users.UserServiceUpdateAvatarArgs
	_args.Req = req
	var _result users.UserServiceUpdateAvatarResult
	if err = p.c.Call(ctx, "UpdateAvatar", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, req *users.ChangePasswordRequest) (r *users.ChangePasswordResponse, err error) {
	var _args users.UserServiceChangePasswordArgs
	_args.Req = req
	var _result users.UserServiceChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
