// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"HuaTug.com/cmd/api/router/relations"
	"HuaTug.com/cmd/api/router/users"
	"HuaTug.com/cmd/api/router/videos"
	"HuaTug.com/cmd/api/router/interactions"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!


	users.Register(r)

	videos.Register(r)

	relations.Register(r)

	interactions.Register(r)

}
